# Generated by Django 5.0.1 on 2024-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('D', 'Dollar'), ('R', 'Rubles')], default='R', max_length=1),
        ),
    ]
